sudo: required
services:
   - docker

before_install:
   - docker build -t junymathew84/docker-react -f Dockerfile.dev .

script:
   - docker run  junymathew84/docker-react npm run test -- --coverage
